/* Optional smoke check. Requires Playwright; the site itself has no dependencies. */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');

(async () => {
  const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_CHANNEL ? { channel: process.env.BROWSER_CHANNEL } : {}) });
  const base = process.argv[2] || 'http://127.0.0.1:8765';
  const output = process.env.SCREENSHOT_DIR || os.tmpdir();
  const errors = [];
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
    page.on('pageerror', e => errors.push(e.message));
    page.on('response', r => { if (r.url().startsWith(base) && r.status() >= 400) errors.push(`${r.status()} ${r.url()}`); });
    await page.goto(base);
    await page.evaluate(async () => {
      document.querySelectorAll('img').forEach(img => { img.loading = 'eager'; });
      await Promise.all([...document.querySelectorAll('img[src]')].map(img => new Promise((resolve, reject) => {
        if (img.complete) return img.naturalWidth ? resolve() : reject(new Error(img.src));
        img.addEventListener('load', resolve, { once: true });
        img.addEventListener('error', () => reject(new Error(img.src)), { once: true });
      })));
      await document.fonts.ready;
    });
    assert.equal(await page.locator('[data-preview]').count(), 5);
    assert.equal(await page.locator('a[download]').count(), 2, 'Keep both installers in one section');
    assert.equal(await page.locator('#download a[download]').count(), 2);
    assert.equal(await page.locator('.s-hero__actions a').count(), 2);
    assert.equal(await page.locator('.s-hero__actions .btn--primary').getAttribute('href'), '#download');
    assert.equal(await page.locator('.hdr .btn').count(), 0);
    assert.equal(await page.locator('.shot.is-missing').count(), 0);
    const content = await page.locator('body').innerText();
    assert(!/canva|[\u2013\u2014]/i.test(content), 'Old wording or long dash in visible copy');
    assert(!/canva|[\u2013\u2014]/i.test(await page.title()));
    const missingAnchors = await page.locator('a[href^="#"]').evaluateAll(links => links.map(a => a.getAttribute('href')).filter(h => h.length > 1 && !document.getElementById(h.slice(1))));
    assert.deepEqual(missingAnchors, []);
    for (const width of [1440, 768, 390]) {
      await page.setViewportSize({ width, height: 1000 });
      await page.evaluate(() => scrollTo(0, 0));
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Horizontal overflow at ${width}`);
      await page.screenshot({ path: path.join(output, `aimaestro-site-${width}.png`) });
    }
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.locator('.s-workflow__shots').screenshot({ path: path.join(output, 'aimaestro-site-workflow.png') });
    const preview = page.locator('[data-preview]').first();
    await preview.click();
    assert(await page.locator('dialog').evaluate(d => d.open));
    assert(await page.locator('.preview__close').evaluate(b => b === document.activeElement));
    await page.keyboard.press('Escape');
    assert(!(await page.locator('dialog').evaluate(d => d.open)));
    assert(await preview.evaluate(a => a === document.activeElement), 'Focus must return to preview');
    assert.equal(await page.locator('body').evaluate(b => b.style.overflow), '');
    await page.locator('[data-refusal-dot]').nth(1).click();
    assert.equal(await page.locator('[data-refusal-idx]').innerText(), '02');
    const faq = page.locator('[data-accordion] details').first();
    await faq.locator('summary').click();
    assert(await faq.evaluate(d => d.open));
    await page.setViewportSize({ width: 390, height: 844 });
    await page.locator('.burger').click();
    assert.equal(await page.locator('.burger').getAttribute('aria-expanded'), 'true');
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('.burger').getAttribute('aria-expanded'), 'false');
    const plain = await browser.newPage({ javaScriptEnabled: false });
    await plain.goto(base);
    assert.equal(await plain.locator('.s-hero img').count(), 0);
    assert(await plain.locator('[data-preview] img').first().isVisible());
    assert((await plain.locator('[data-preview]').first().getAttribute('href')).endsWith('.webp'));
    const fallback = await browser.newPage();
    await fallback.route('**/results.webp', route => route.abort());
    await fallback.goto(base);
    await fallback.locator('[src="assets/screenshots/results.webp"]').scrollIntoViewIfNeeded();
    await fallback.locator('.shot.is-missing').first().waitFor();
    const animated = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'no-preference' });
    animated.on('pageerror', e => errors.push(e.message));
    await animated.goto(base);
    assert.equal(await animated.locator('.s-hero img').count(), 0);
    const card = animated.locator('.card').first();
    await card.scrollIntoViewIfNeeded();
    await animated.waitForFunction(() => getComputedStyle(document.querySelector('.s-features__item')).opacity === '1');
    const box = await card.boundingBox();
    const shadowBefore = await card.evaluate(el => getComputedStyle(el).boxShadow);
    await card.hover({ position: { x: 30, y: 30 } });
    await animated.waitForFunction(() => document.querySelector('.card').classList.contains('is-lit'));
    const glow = card.locator('.card__glow-light');
    const background = await card.evaluate(el => getComputedStyle(el).backgroundImage);
    await animated.mouse.move(box.x + box.width - 35, box.y + 75);
    const target = box.width - 35;
    const firstX = await glow.evaluate(el => new DOMMatrix(getComputedStyle(el).transform).m41);
    assert(firstX < target - 1, 'Pointer light should interpolate rather than snap');
    await animated.waitForFunction(x => Math.abs(new DOMMatrix(getComputedStyle(document.querySelector('.card__glow-light')).transform).m41 - x) < 1, target);
    assert.equal(await card.evaluate(el => getComputedStyle(el).backgroundImage), background, 'Tracking must not repaint a changing gradient');
    assert.notEqual(await card.evaluate(el => getComputedStyle(el).boxShadow), shadowBefore);
    const after = await card.boundingBox();
    assert(Math.abs(box.x - after.x) < .1 && Math.abs(box.y - after.y) < .1, 'Card hit area must stay still');
    await animated.screenshot({ path: path.join(output, 'aimaestro-site-hover.png') });
    await animated.mouse.move(box.x - 10, box.y + 75);
    assert(!(await card.evaluate(el => el.classList.contains('is-lit'))));
    const fading = await card.locator('.card__glow').evaluate(el => Number(getComputedStyle(el).opacity));
    assert(fading > 0, 'Light should fade out instead of disappearing');
    await animated.mouse.move(box.x + 35, box.y + 75);
    assert(await glow.evaluate(el => new DOMMatrix(getComputedStyle(el).transform).m41) > 36, 'Re-entry must retain the visible light position');
    await animated.waitForFunction(() => Math.abs(new DOMMatrix(getComputedStyle(document.querySelector('.card__glow-light')).transform).m41 - 35) < 1);
    await animated.evaluate(() => scrollBy({ top: 25, behavior: 'instant' }));
    await animated.waitForFunction(() => Math.abs(new DOMMatrix(getComputedStyle(document.querySelector('.card__glow-light')).transform).m42 - 100) < 1);
    assert(await card.evaluate(el => el.classList.contains('is-lit')), 'Scrolling within a card should keep tracking');
    await animated.emulateMedia({ reducedMotion: 'reduce' });
    await animated.mouse.move(box.x + 50, box.y + 80);
    assert(!(await card.evaluate(el => el.classList.contains('is-lit'))));
    assert.equal(await card.locator('.card__glow').evaluate(el => getComputedStyle(el).display), 'none');
    assert.equal(await animated.locator('[data-wf-pulse]').evaluate(el => getComputedStyle(el).opacity), '0');
    await animated.emulateMedia({ reducedMotion: 'no-preference' });
    const detail = animated.locator('[data-accordion] details').first();
    const question = detail.locator('summary');
    await question.click();
    await animated.waitForTimeout(60);
    await question.click();
    await animated.waitForTimeout(60);
    await question.click();
    await animated.waitForFunction(() => {
      const d = document.querySelector('[data-accordion] details');
      return d.open && !d.querySelector('[data-panel]').getAnimations().length;
    });
    assert(await detail.locator('[data-panel]').evaluate(el => el.getBoundingClientRect().height > 20));
    await question.press('Enter');
    await animated.waitForFunction(() => !document.querySelector('[data-accordion] details').open);
    assert.deepEqual(errors, []);
    console.log('Passed: consolidated downloads; 5 images; no hero image; transform glow; smooth fade/re-entry/scroll tracking; stable hover bounds; live reduced-motion preference; interrupted FAQ animation; copy; anchors; 3 responsive widths; modal focus/Escape; navigation; FAQ; refusal selector; no-JS links; missing-image fallback; no console or local HTTP errors.');
    console.log(`Visual previews: ${output}`);
  } finally {
    await browser.close();
  }
})().catch(e => { console.error(e); process.exitCode = 1; });
